#!/bin/sh
cd "${0%/*}" || exit                        # Run from this directory
# -----------------------------------------------------------------------------

wclean MeshSmoother
wclean extBlockMesh
wclean hexMeshSmoother

# -----------------------------------------------------------------------------
