#!/bin/sh
cd "${0%/*}" || exit                        # Run from this directory
# -----------------------------------------------------------------------------
if [ -f "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments ]
then
    . "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments
fi
# -----------------------------------------------------------------------------

wmake MeshSmoother
wmake extBlockMesh
wmake hexMeshSmoother

# -----------------------------------------------------------------------------
